# Generated by Django 4.1.4 on 2023-02-26 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='room',
            new_name='space',
        ),
    ]
