# Generated by Django 4.1.4 on 2023-02-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_appuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
